ARG PYTHON_BASE_IMAGE=foodmind-python-dependencies:local

FROM ${PYTHON_BASE_IMAGE}

WORKDIR /app

COPY app ./app
COPY cmd ./cmd
COPY alembic ./alembic
COPY alembic.ini ./
COPY elasticsearch ./elasticsearch

EXPOSE 8000

CMD ["uvicorn", "app.api.middleware:app", "--host", "0.0.0.0", "--port", "8000"]
