// Grafana dashboard source. Render it with `make grafana-dashboards`.
local target(expression, legend) = {
  expr: expression,
  legendFormat: legend,
  refId: 'A',
};

local panel(id, title, expression, legend, x, y, unit='short') = {
  id: id,
  title: title,
  type: 'timeseries',
  datasource: { type: 'prometheus', uid: 'prometheus' },
  gridPos: { h: 8, w: 12, x: x, y: y },
  fieldConfig: {
    defaults: { unit: unit },
    overrides: [],
  },
  options: {
    legend: { displayMode: 'table', placement: 'bottom', showLegend: true },
    tooltip: { mode: 'multi', sort: 'desc' },
  },
  targets: [target(expression, legend)],
};

{
  annotations: { list: [] },
  editable: true,
  graphTooltip: 1,
  links: [
    {
      title: 'Explore FoodMind traces',
      type: 'link',
      url: '/explore?left={"datasource":"tempo"}',
    },
  ],
  panels: [
    panel(
      1,
      'API request rate',
      'sum by (method, path, status) (rate(foodmind_api_requests_total[$__rate_interval]))',
      '{{method}} {{path}} · {{status}}',
      0,
      0,
      'reqps',
    ),
    panel(
      2,
      'API latency p95',
      'histogram_quantile(0.95, sum by (le, method, path) (rate(foodmind_api_request_duration_seconds_bucket[$__rate_interval])))',
      '{{method}} {{path}}',
      12,
      0,
      's',
    ),
    panel(
      3,
      'Orchestrator run rate',
      'sum by (route, outcome) (rate(foodmind_orchestrator_runs_total[$__rate_interval]))',
      '{{route}} · {{outcome}}',
      0,
      8,
      'ops',
    ),
    panel(
      4,
      'Orchestrator latency p95',
      'histogram_quantile(0.95, sum by (le, route, outcome) (rate(foodmind_orchestrator_duration_seconds_bucket[$__rate_interval])))',
      '{{route}} · {{outcome}}',
      12,
      8,
      's',
    ),
    panel(
      5,
      'Processing stage latency p95',
      'histogram_quantile(0.95, sum by (le, stage, outcome) (rate(foodmind_orchestrator_stage_duration_seconds_bucket[$__rate_interval])))',
      '{{stage}} · {{outcome}}',
      0,
      16,
      's',
    ),
    panel(
      6,
      'Specialist agent executions',
      'sum by (agent, outcome, cached) (rate(foodmind_agent_runs_total[$__rate_interval]))',
      '{{agent}} · {{outcome}} · cache={{cached}}',
      12,
      16,
      'ops',
    ),
    panel(
      7,
      'Specialist agent latency p95',
      'histogram_quantile(0.95, sum by (le, agent, outcome) (rate(foodmind_agent_duration_seconds_bucket{cached="false"}[$__rate_interval])))',
      '{{agent}} · {{outcome}}',
      0,
      24,
      's',
    ),
    panel(
      8,
      'Tool and retrieval operations',
      'sum by (agent, tool, outcome) (rate(foodmind_tool_calls_total[$__rate_interval]))',
      '{{agent}} · {{tool}} · {{outcome}}',
      12,
      24,
      'ops',
    ),
    panel(
      9,
      'LLM token use',
      'sum by (component, agent, model, direction) (increase(foodmind_llm_tokens_total[$__interval]))',
      '{{component}} · {{agent}} · {{direction}}',
      0,
      32,
      'tokens',
    ),
    panel(
      10,
      'LLM run outcomes',
      'sum by (component, agent, model, outcome) (rate(foodmind_llm_requests_total[$__rate_interval]))',
      '{{component}} · {{agent}} · {{outcome}}',
      12,
      32,
      'ops',
    ),
    panel(
      11,
      'Message processing latency p95',
      'histogram_quantile(0.95, sum by (le, step, outcome) (rate(foodmind_message_processing_step_duration_seconds_bucket[$__rate_interval])))',
      '{{step}} · {{outcome}}',
      0,
      40,
      's',
    ),
    panel(
      12,
      'Feedback submissions',
      'sum by (is_useful) (increase(foodmind_feedback_submissions_total[$__interval]))',
      'useful={{is_useful}}',
      12,
      40,
      'short',
    ),
    panel(
      13,
      'Repository retrieval latency p95',
      'histogram_quantile(0.95, sum by (le, operation, outcome, cache) (rate(foodmind_retrieval_duration_seconds_bucket[$__rate_interval])))',
      '{{operation}} · {{outcome}} · cache={{cache}}',
      0,
      48,
      's',
    ),
    panel(
      14,
      'Useful-feedback ratio',
      'sum(increase(foodmind_feedback_submissions_total{is_useful="true"}[$__interval])) / clamp_min(sum(increase(foodmind_feedback_submissions_total[$__interval])), 1)',
      'useful feedback ratio',
      12,
      48,
      'percentunit',
    ),
    panel(
      15,
      'Total LLM tokens',
      'sum by (direction) (increase(foodmind_llm_tokens_total[$__interval]))',
      '{{direction}}',
      0,
      56,
      'tokens',
    ),
  ],
  refresh: '30s',
  schemaVersion: 41,
  tags: ['foodmind', 'orchestrator'],
  templating: { list: [] },
  time: { from: 'now-6h', to: 'now' },
  timezone: 'browser',
  title: 'FoodMind Overview',
  uid: 'foodmind-overview',
  version: 1,
}
