{{- if and (or (eq .Values.component "all") (eq .Values.component "api")) .Values.public.apiEnabled }}
{{- if .Values.public.apiHost }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.public.managedCertificateName }}
spec:
  domains: [{{ .Values.public.apiHost | quote }}]
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.public.staticIpName | quote }}
    {{- if .Values.public.apiHost }}
    networking.gke.io/managed-certificates: {{ .Values.public.managedCertificateName | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.public.apiHost }}
    - host: {{ .Values.public.apiHost | quote }}
    {{- else }}
    -
    {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: api, port: {number: 8000}}
{{- end }}
