{{- if or (eq .Values.component "all") (eq .Values.component "bootstrap") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foodmind
  labels:
    {{- include "foodmind.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "gcpServiceAccount is required" .Values.gcpServiceAccount | quote }}
{{- end }}
