"""Class-based PydanticAI food-search agent and repository tools."""

import asyncio
from dataclasses import dataclass, field
from enum import StrEnum
from time import perf_counter
from typing import Any, Awaitable, Callable, TypeVar, cast

from elasticsearch import AsyncElasticsearch
from pydantic import BaseModel, Field
from pydantic_ai import Agent, AgentRunResult, RunContext
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

from app.aggregates import BrandedFood, FoodEntity, FoundationFood, OpenFoodFactsProduct
from app.repositories.openfoodfacts import OpenFoodFactsRepository
from app.repositories.queries import (
    BrandedFoodQuery,
    OpenFoodFactsQuery,
    SearchQuery,
    USDAFoodQuery,
    WikidataFoodQuery,
)
from app.repositories.usda import USDARepository
from app.repositories.wikidata import WikidataFoodRepository
from app.observability import metrics
from app.observability.tracing import tracing
from app.settings import get_settings

QueryT = TypeVar("QueryT", bound=SearchQuery)


class FoodSource(StrEnum):
    """Identify a catalog source that can answer a food search."""

    WIKIDATA = "wikidata"
    USDA_FOUNDATION = "usda_foundation"
    USDA_BRANDED = "usda_branded"
    OPENFOODFACTS = "openfoodfacts"


class FoodSearchRequest(BaseModel):
    """Validated search criteria exposed to the agent as a tool argument.

    Attributes:
        text: Free-text food name or product query.
        ingredient: Ingredient text to search for.
        cuisine: Cuisine identifier or name.
        country: Country identifier or name.
        brand: Brand name.
        category: Food category.
        source: Optional source to search exclusively.
        limit: Maximum number of results.
    """

    text: str | None = None
    ingredient: str | None = None
    cuisine: str | None = None
    country: str | None = None
    brand: str | None = None
    category: str | None = None
    source: FoodSource | None = None
    limit: int = Field(default=10, ge=1, le=50)


class FoodSearchResult(BaseModel):
    """Compact, source-neutral food result returned by the search tool.

    Attributes:
        id: Canonical identifier of the food.
        label: Human-readable food label.
        source: Data source that supplied the result.
        entity_type: Domain entity type.
        description: Optional description.
    """

    id: str
    label: str
    source: str
    entity_type: str
    description: str | None = None


class FoodSearchAnswer(BaseModel):
    """Typed answer returned by the food-search agent.

    Attributes:
        answer: Natural-language summary generated by the agent.
        results: Catalog records used to produce the summary.
    """

    answer: str
    results: list[FoodSearchResult] = Field(default_factory=list)


@dataclass
class FoodSearchDependencies:
    """Repositories available to one agent run.

    Attributes:
        wikidata: Repository for Wikidata food concepts.
        usda: Repository for USDA Foundation and Branded Foods.
        openfoodfacts: Repository for Open Food Facts products.
    """

    wikidata: WikidataFoodRepository
    usda: USDARepository
    openfoodfacts: OpenFoodFactsRepository
    retrieval_approach: str | None = None
    retrieval_timeout_seconds: float = 5.0
    _request_cache: dict[str, asyncio.Task[Any]] = field(default_factory=dict)

    @classmethod
    def from_client(
        cls, client: AsyncElasticsearch, retrieval_approach: str | None = None
    ) -> "FoodSearchDependencies":
        """Build repositories over one shared Elasticsearch client.

        Args:
            client: Open Elasticsearch client managed by the application.

        Returns:
            Dependencies containing lightweight repository wrappers.
        """
        return cls(
            wikidata=WikidataFoodRepository(client),
            usda=USDARepository(client),
            openfoodfacts=OpenFoodFactsRepository(client),
            retrieval_approach=retrieval_approach,
            retrieval_timeout_seconds=get_settings().RETRIEVAL_TIMEOUT_SECONDS,
        )

    def reset_request_cache(self) -> None:
        """Discard cached retrieval tasks at the beginning of a user request."""
        self._request_cache.clear()

    async def search_wikidata(self, query: WikidataFoodQuery) -> list[FoodEntity]:
        """Search Wikidata once per normalized query within one request."""
        query = self._bounded(query)
        return cast(
            list[FoodEntity],
            await self._cached("wikidata.search", query, lambda: self.wikidata.search(query)),
        )

    async def get_wikidata(self, entity_id: str) -> FoodEntity | None:
        """Look up a Wikidata entity once per request."""
        return cast(
            FoodEntity | None,
            await self._cached(
                "wikidata.get", entity_id,
                lambda: self.wikidata.get_by_id(entity_id),
            ),
        )

    async def search_foundations(
        self, query: USDAFoodQuery
    ) -> list[FoundationFood]:
        """Search USDA Foundation once per normalized query within one request."""
        query = self._bounded(query)
        return cast(
            list[FoundationFood],
            await self._cached(
                "usda.foundation.search",
                query,
                lambda: self.usda.search_foundations(query),
            ),
        )

    async def search_branded(self, query: BrandedFoodQuery) -> list[BrandedFood]:
        """Search USDA Branded once per normalized query within one request."""
        query = self._bounded(query)
        return cast(
            list[BrandedFood],
            await self._cached(
                "usda.branded.search",
                query,
                lambda: self.usda.search_branded(query),
            ),
        )

    async def search_openfoodfacts(
        self, query: OpenFoodFactsQuery
    ) -> list[OpenFoodFactsProduct]:
        """Search Open Food Facts once per normalized query within one request."""
        query = self._bounded(query)
        return cast(
            list[OpenFoodFactsProduct],
            await self._cached(
                "openfoodfacts.search",
                query,
                lambda: self.openfoodfacts.search(query),
            ),
        )

    async def _cached(
        self,
        operation: str,
        query: object,
        call: Callable[[], Awaitable[Any]],
    ) -> Any:
        """Share an in-flight retrieval task and bound its latency."""
        serialized = query.model_dump_json() if isinstance(query, BaseModel) else str(query)
        key = f"{operation}:{serialized}"
        task = self._request_cache.get(key)
        cache_status = "hit" if task is not None else "miss"
        if task is None:
            async def execute_call() -> Any:
                """Adapt a generic awaitable to a task coroutine."""
                return await call()

            task = asyncio.create_task(execute_call())
            self._request_cache[key] = task
        started = perf_counter()
        with tracing.span(
            "foodmind.retrieval",
            {
                "foodmind.operation": operation,
                "foodmind.cache": cache_status,
            },
        ) as span:
            try:
                result = await asyncio.wait_for(
                    asyncio.shield(task), timeout=self.retrieval_timeout_seconds
                )
            except Exception:
                self._request_cache.pop(key, None)
                span.set_attribute("foodmind.outcome", "error")
                metrics.record_retrieval(
                    operation=operation,
                    outcome="error",
                    cache=cache_status,
                    duration_seconds=perf_counter() - started,
                )
                raise
            span.set_attribute("foodmind.outcome", "success")
        metrics.record_retrieval(
            operation=operation,
            outcome="success",
            cache=cache_status,
            duration_seconds=perf_counter() - started,
        )
        return result

    @staticmethod
    def _bounded(query: QueryT) -> QueryT:
        """Cap source results before they enter an agent's model context."""
        maximum = get_settings().MAX_RETRIEVAL_RESULTS
        return query.model_copy(update={"limit": min(query.limit, maximum)})


@dataclass
class FoodSearchAgent:
    """Search food data through repository-backed PydanticAI tools.

    The class owns the PydanticAI agent and tool registration, while repository
    dependencies remain request-scoped and are supplied to :meth:`run`.
    """

    instructions: str | None = None
    agent: Agent[FoodSearchDependencies, FoodSearchAnswer] = field(init=False)

    def __post_init__(self) -> None:
        """Create the PydanticAI agent and register its tools once."""
        shared_instructions = (
            "You search the FoodMind food catalog. Use the search_foods tool "
            "for catalog questions and lookup_wikidata_entity for a specific "
            "Wikidata entity. Summarize only returned results and never "
            "invent food data. Call search_foods at most once per request. "
            "Only call lookup_wikidata_entity for an exact identifier returned "
            "by search_foods, and call it at most once. After receiving tool "
            "results, provide the final answer immediately."
        )
        settings = get_settings()
        model = settings.OPENAI_AGENT_MODEL or settings.OPENAI_MODEL
        if settings.OPENAI_API_KEY:
            model = OpenAIChatModel(
                model_name=model.removeprefix("openai:"),
                provider=OpenAIProvider(api_key=settings.OPENAI_API_KEY),
            )
        self.agent = Agent(
            model,
            deps_type=FoodSearchDependencies,
            output_type=FoodSearchAnswer,
            instructions=f"{shared_instructions} {self.instructions or ''}".strip(),
            defer_model_check=not bool(settings.OPENAI_API_KEY),
        )
        self.agent.tool(self.search_foods)
        self.agent.tool(self.lookup_wikidata_entity)

    async def run(
        self, prompt: str, *, deps: FoodSearchDependencies
    ) -> AgentRunResult[FoodSearchAnswer]:
        """Run the agent with repositories supplied by the application boundary.

        Args:
            prompt: User's natural-language food search request.
            deps: Repository dependencies for this run.

        Returns:
            Typed agent response containing a summary and search results.
        """
        settings = get_settings()
        model = settings.OPENAI_AGENT_MODEL or settings.OPENAI_MODEL
        with tracing.span(
            "foodmind.llm.agent", {"foodmind.agent": "food_search"}
        ) as span:
            try:
                result = await self.agent.run(prompt, deps=deps)
            except Exception:
                span.set_attribute("foodmind.outcome", "error")
                metrics.record_llm_failure(
                    component="agent", agent="food_search", model=model
                )
                raise
            span.set_attribute("foodmind.outcome", "success")
            span.set_attribute("gen_ai.request.model", model.removeprefix("openai:"))
            span.set_attribute("gen_ai.usage.input_tokens", result.usage.input_tokens)
            span.set_attribute("gen_ai.usage.output_tokens", result.usage.output_tokens)
        metrics.record_llm_usage(
            component="agent",
            agent="food_search",
            model=model,
            usage=result.usage,
        )
        return result

    async def search_foods(
        self,
        ctx: RunContext[FoodSearchDependencies],
        request: FoodSearchRequest,
    ) -> list[FoodSearchResult]:
        """Search one or all repositories using the supplied filters.

        Args:
            ctx: PydanticAI context containing repository dependencies.
            request: Validated search criteria.

        Returns:
            Compact, source-neutral search results.
        """
        text = request.text or request.ingredient
        match request.source:
            case FoodSource.WIKIDATA:
                foods = await ctx.deps.search_wikidata(
                    WikidataFoodQuery(
                        text=text,
                        cuisine_id=request.cuisine,
                        country_id=request.country,
                        limit=request.limit,
                    )
                )
            case FoodSource.USDA_FOUNDATION:
                foods = await ctx.deps.search_foundations(
                    USDAFoodQuery(
                        text=text, category=request.category, limit=request.limit
                    )
                )
            case FoodSource.USDA_BRANDED:
                foods = await ctx.deps.search_branded(
                    BrandedFoodQuery(
                        text=text,
                        category=request.category,
                        brand=request.brand,
                        limit=request.limit,
                    )
                )
            case FoodSource.OPENFOODFACTS:
                foods = await ctx.deps.search_openfoodfacts(
                    OpenFoodFactsQuery(
                        text=text,
                        barcode=request.text
                        if request.text and request.text.isdigit()
                        else None,
                        brand=request.brand,
                        country=request.country,
                        limit=request.limit,
                    )
                )
            case None:
                groups = await asyncio.gather(
                    ctx.deps.search_wikidata(
                        WikidataFoodQuery(
                            text=text,
                            cuisine_id=request.cuisine,
                            country_id=request.country,
                            limit=request.limit,
                        )
                    ),
                    ctx.deps.search_foundations(
                        USDAFoodQuery(
                            text=text, category=request.category, limit=request.limit
                        )
                    ),
                    ctx.deps.search_branded(
                        BrandedFoodQuery(
                            text=text,
                            category=request.category,
                            brand=request.brand,
                            limit=request.limit,
                        )
                    ),
                    ctx.deps.search_openfoodfacts(
                        OpenFoodFactsQuery(
                            text=text,
                            brand=request.brand,
                            country=request.country,
                            limit=request.limit,
                        )
                    ),
                )
                foods = [food for group in groups for food in group][: request.limit]
        return [self._result(food) for food in foods]

    async def lookup_wikidata_entity(
        self,
        ctx: RunContext[FoodSearchDependencies],
        entity_id: str,
    ) -> FoodSearchResult | None:
        """Look up one Wikidata food entity by identifier.

        Args:
            ctx: PydanticAI context containing repository dependencies.
            entity_id: Wikidata identifier, with or without its prefix.

        Returns:
            The matching result, or ``None`` when it does not exist.
        """
        food = await ctx.deps.get_wikidata(entity_id)
        return self._result(food) if food is not None else None

    @staticmethod
    def _result(
        food: FoodEntity | FoundationFood | BrandedFood | OpenFoodFactsProduct,
    ) -> FoodSearchResult:
        """Convert a domain object into the agent's compact result shape.

        Args:
            food: Domain food object returned by a repository.

        Returns:
            Source-neutral result suitable for the agent output.
        """
        source = "wikidata" if isinstance(food, FoodEntity) else food.source
        entity_type = (
            "food_concept" if isinstance(food, FoodEntity) else food.entity_type
        )
        return FoodSearchResult(
            id=food.id,
            label=food.label,
            source=source,
            entity_type=entity_type,
            description=food.description,
        )
