"""Class-based PydanticAI food-search agent and repository tools."""

import asyncio
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from elasticsearch import AsyncElasticsearch
from pydantic import BaseModel, Field
from pydantic_ai import Agent, AgentRunResult, RunContext

from app.aggregates import BrandedFood, FoodEntity, FoundationFood, OpenFoodFactsProduct
from app.agents.foodmind import _create_model
from app.repositories.openfoodfacts import OpenFoodFactsRepository
from app.repositories.queries import (
    BrandedFoodQuery,
    OpenFoodFactsQuery,
    USDAFoodQuery,
    WikidataFoodQuery,
)
from app.repositories.usda import USDARepository
from app.repositories.wikidata import WikidataFoodRepository
from app.settings import get_settings


class FoodSource(StrEnum):
    """Identify a catalog source that can answer a food search."""

    WIKIDATA = "wikidata"
    USDA_FOUNDATION = "usda_foundation"
    USDA_BRANDED = "usda_branded"
    OPENFOODFACTS = "openfoodfacts"


class FoodSearchRequest(BaseModel):
    """Validated search criteria exposed to the agent as a tool argument.

    Attributes:
        text: Free-text food name or product query.
        ingredient: Ingredient text to search for.
        cuisine: Cuisine identifier or name.
        country: Country identifier or name.
        brand: Brand name.
        category: Food category.
        source: Optional source to search exclusively.
        limit: Maximum number of results.
    """

    text: str | None = None
    ingredient: str | None = None
    cuisine: str | None = None
    country: str | None = None
    brand: str | None = None
    category: str | None = None
    source: FoodSource | None = None
    limit: int = Field(default=10, ge=1, le=50)


class FoodSearchResult(BaseModel):
    """Compact, source-neutral food result returned by the search tool.

    Attributes:
        id: Canonical identifier of the food.
        label: Human-readable food label.
        source: Data source that supplied the result.
        entity_type: Domain entity type.
        description: Optional description.
    """

    id: str
    label: str
    source: str
    entity_type: str
    description: str | None = None


class FoodSearchAnswer(BaseModel):
    """Typed answer returned by the food-search agent.

    Attributes:
        answer: Natural-language summary generated by the agent.
        results: Catalog records used to produce the summary.
    """

    answer: str
    results: list[FoodSearchResult] = Field(default_factory=list)


@dataclass
class FoodSearchDependencies:
    """Repositories available to one agent run.

    Attributes:
        wikidata: Repository for Wikidata food concepts.
        usda: Repository for USDA Foundation and Branded Foods.
        openfoodfacts: Repository for Open Food Facts products.
    """

    wikidata: WikidataFoodRepository
    usda: USDARepository
    openfoodfacts: OpenFoodFactsRepository

    @classmethod
    def from_client(cls, client: AsyncElasticsearch) -> "FoodSearchDependencies":
        """Build repositories over one shared Elasticsearch client.

        Args:
            client: Open Elasticsearch client managed by the application.

        Returns:
            Dependencies containing lightweight repository wrappers.
        """
        return cls(
            wikidata=WikidataFoodRepository(client),
            usda=USDARepository(client),
            openfoodfacts=OpenFoodFactsRepository(client),
        )


@dataclass
class FoodSearchAgent:
    """Search food data through repository-backed PydanticAI tools.

    The class owns the PydanticAI agent and tool registration, while repository
    dependencies remain request-scoped and are supplied to :meth:`run`.
    """

    instructions: str | None = None
    agent: Agent[FoodSearchDependencies, FoodSearchAnswer] = field(init=False)

    def __post_init__(self) -> None:
        """Create the PydanticAI agent and register its tools once."""
        shared_instructions = (
            "You search the FoodMind food catalog. Use the search_foods tool "
            "for catalog questions and lookup_wikidata_entity for a specific "
            "Wikidata entity. Summarize only returned results and never "
            "invent food data. Call search_foods at most once per request. "
            "Only call lookup_wikidata_entity for an exact identifier returned "
            "by search_foods, and call it at most once. After receiving tool "
            "results, provide the final answer immediately."
        )
        settings = get_settings()
        model: Any = (
            _create_model()
            if settings.OPENAI_API_KEY
            else settings.OPENAI_MODEL
        )
        self.agent = Agent(
            model,
            deps_type=FoodSearchDependencies,
            output_type=FoodSearchAnswer,
            instructions=f"{shared_instructions} {self.instructions or ''}".strip(),
            defer_model_check=not bool(settings.OPENAI_API_KEY),
        )
        self.agent.tool(self.search_foods)
        self.agent.tool(self.lookup_wikidata_entity)

    async def run(
        self, prompt: str, *, deps: FoodSearchDependencies
    ) -> AgentRunResult[FoodSearchAnswer]:
        """Run the agent with repositories supplied by the application boundary.

        Args:
            prompt: User's natural-language food search request.
            deps: Repository dependencies for this run.

        Returns:
            Typed agent response containing a summary and search results.
        """
        return await self.agent.run(prompt, deps=deps)

    async def search_foods(
        self,
        ctx: RunContext[FoodSearchDependencies],
        request: FoodSearchRequest,
    ) -> list[FoodSearchResult]:
        """Search one or all repositories using the supplied filters.

        Args:
            ctx: PydanticAI context containing repository dependencies.
            request: Validated search criteria.

        Returns:
            Compact, source-neutral search results.
        """
        text = request.text or request.ingredient
        match request.source:
            case FoodSource.WIKIDATA:
                foods = await ctx.deps.wikidata.search(
                    WikidataFoodQuery(
                        text=text,
                        cuisine_id=request.cuisine,
                        country_id=request.country,
                        limit=request.limit,
                    )
                )
            case FoodSource.USDA_FOUNDATION:
                foods = await ctx.deps.usda.search_foundations(
                    USDAFoodQuery(
                        text=text, category=request.category, limit=request.limit
                    )
                )
            case FoodSource.USDA_BRANDED:
                foods = await ctx.deps.usda.search_branded(
                    BrandedFoodQuery(
                        text=text,
                        category=request.category,
                        brand=request.brand,
                        limit=request.limit,
                    )
                )
            case FoodSource.OPENFOODFACTS:
                foods = await ctx.deps.openfoodfacts.search(
                    OpenFoodFactsQuery(
                        text=text,
                        barcode=request.text
                        if request.text and request.text.isdigit()
                        else None,
                        brand=request.brand,
                        country=request.country,
                        limit=request.limit,
                    )
                )
            case None:
                groups = await asyncio.gather(
                    ctx.deps.wikidata.search(
                        WikidataFoodQuery(
                            text=text,
                            cuisine_id=request.cuisine,
                            country_id=request.country,
                            limit=request.limit,
                        )
                    ),
                    ctx.deps.usda.search_foundations(
                        USDAFoodQuery(
                            text=text, category=request.category, limit=request.limit
                        )
                    ),
                    ctx.deps.usda.search_branded(
                        BrandedFoodQuery(
                            text=text,
                            category=request.category,
                            brand=request.brand,
                            limit=request.limit,
                        )
                    ),
                    ctx.deps.openfoodfacts.search(
                        OpenFoodFactsQuery(
                            text=text,
                            brand=request.brand,
                            country=request.country,
                            limit=request.limit,
                        )
                    ),
                )
                foods = [food for group in groups for food in group][: request.limit]
        return [self._result(food) for food in foods]

    async def lookup_wikidata_entity(
        self,
        ctx: RunContext[FoodSearchDependencies],
        entity_id: str,
    ) -> FoodSearchResult | None:
        """Look up one Wikidata food entity by identifier.

        Args:
            ctx: PydanticAI context containing repository dependencies.
            entity_id: Wikidata identifier, with or without its prefix.

        Returns:
            The matching result, or ``None`` when it does not exist.
        """
        food = await ctx.deps.wikidata.get_by_id(entity_id)
        return self._result(food) if food is not None else None

    @staticmethod
    def _result(
        food: FoodEntity | FoundationFood | BrandedFood | OpenFoodFactsProduct,
    ) -> FoodSearchResult:
        """Convert a domain object into the agent's compact result shape.

        Args:
            food: Domain food object returned by a repository.

        Returns:
            Source-neutral result suitable for the agent output.
        """
        source = "wikidata" if isinstance(food, FoodEntity) else food.source
        entity_type = (
            "food_concept" if isinstance(food, FoodEntity) else food.entity_type
        )
        return FoodSearchResult(
            id=food.id,
            label=food.label,
            source=source,
            entity_type=entity_type,
            description=food.description,
        )


def create_food_search_agent() -> FoodSearchAgent:
    """Create a configured food-search agent.

    Returns:
        A new agent instance with its repository tools registered.
    """
    return FoodSearchAgent()
